### ISSUE TITLE
Ledger Nano X stopped working with Tezos Reward Distributor

### ISSUE THREAD

**Issue by songproducer** [LedgerHQ/app-tezos-legacy#41]
```
2022-04-08 01:20:14,729 - consumer0 - ERROR - Batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/Users/leotreasure/tezos-reward-distributor/src/pay/batch_payer.py", line 465, in pay_single_batch
    status, operation_hash, error_message = self.attempt_single_batch(
  File "/Users/leotreasure/tezos-reward-distributor/src/pay/batch_payer.py", line 932, in attempt_single_batch
    signed_bytes = self.clnt_mngr.sign(bytes, self.manager)
  File "/Users/leotreasure/tezos-reward-distributor/src/cli/client_manager.py", line 114, in sign
    raise ClientException(
exception.client.ClientException: Error at signing. Make sure tezos-signer is up and running 'tezos-signer launch http signer': '[{"kind":"permanent","id":"signer.ledger.msg-chunk-too-big","msg":"sign-with-hash"}]
2022-04-08 01:20:14,730 - consumer0 - INFO - Payment of batch 3 succeeded in 1 attempt(s)
```
I did have tezos-signer launch http signer running and it was receiving requests fine.

https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/issues/589

**Comment by songproducer** [comment]
Also tested with Nano S different tz1 address (ED25519) and that had same error msg-chunk-too-big.

**Comment by gregthebaker** [comment]
[I am also experiencing this issue, details posted here originally](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/issues/589#issuecomment-1098056326)
Copied below:
> I am trying to send payments for cycle 465 and I am encountering the following error. The signer is up and running as normal and I am on the ithica2 branch of TRD using a ledger nano S. What's odd is that it doesnt mark the payment as failed either.
> 
> ```
> 2022-04-12 08:56:18,353 - consumer0 - ERROR - Error, request ->POST http://127.0.0.1:6732/keys/<baker_address><-, params ->"<_params>"<-,
> ---
> Error, response ->[{"kind":"permanent","id":"signer.ledger.msg-chunk-too-big","msg":"sign-with-hash"}]
> <-
> 2022-04-12 08:56:18,353 - consumer0 - ERROR - Batch payment attempt 1/3 for current batch failed with error
> Traceback (most recent call last):
>   File "/home/user/tezos-reward-distributor/src/pay/batch_payer.py", line 465, in pay_single_batch
>     status, operation_hash, error_message = self.attempt_single_batch(
>   File "/home/user/tezos-reward-distributor/src/pay/batch_payer.py", line 932, in attempt_single_batch
>     signed_bytes = self.clnt_mngr.sign(bytes, self.manager)
>   File "/home/user/tezos-reward-distributor/src/cli/client_manager.py", line 114, in sign
>     raise ClientException(
> exception.client.ClientException: Error at signing. Make sure tezos-signer is up and running 'tezos-signer launch http signer': '[{"kind":"permanent","id":"signer.ledger.msg-chunk-too-big","msg":"sign-with-hash"}]
> '
> 2022-04-12 08:56:18,363 - consumer0 - INFO - Payment of batch 1 succeeded in 1 attempt(s)
> 2022-04-12 08:56:18,364 - consumer0 - INFO - Total amount payed out is 0 mutez in 1 attempts and 1 batches.
> 2022-04-12 08:56:18,364 - consumer0 - INFO - Processing completed for 7 payment items.
> 2022-04-12 08:56:18,364 - consumer0 - INFO - Payment report is created at '/home/user/pymnt/reports/<baker_address>/payments/done/465.csv'
> 2022-04-12 08:56:18,369 - consumer0 - INFO - Calculation report is created at '/home/user/pymnt/reports/<baker_address>/calculations/465.csv'
> 2022-04-12 08:56:18,369 - consumer0 - INFO - Simulated transaction_fees added to calculations file.
> 2022-04-12 08:56:18,369 - consumer0 - INFO - [Plugins] Not sending notification; no plugins enabled
> 2022-04-12 08:56:18,369 - consumer0 - INFO - [Plugins] Not sending notification; no plugins enabled
> 2022-04-12 08:56:18,371 - consumer0 - INFO - Sending anonymous statistics; See docs/statistics.rst for more information.
> 2022-04-12 08:56:21,624 - producer  - INFO - Reward creation is done for cycle 465, created 17 rewards.
> 2022-04-12 08:56:27,058 - producer  - INFO - Checking for pending payments: checking 466 <= 471 - (5 + 1) - 0
> 2022-04-12 08:56:27,058 - producer  - INFO - No pending payments for cycle 466, current cycle is 471
> 2022-04-12 08:56:27,058 - producer  - INFO - Run mode PENDING satisfied. Terminating...
> 2022-04-12 08:56:27,059 - producer  - INFO - Sending KeyboardInterrupt signal.
> 2022-04-12 08:56:27,059 - consumer0 - WARNING - Exit signal received. Terminating...
> 2022-04-12 08:56:27,934 - MainThread - INFO - Interrupted.
> 2022-04-12 08:56:27,934 - MainThread - INFO - TRD is shutting down...
> 2022-04-12 08:56:27,934 - MainThread - INFO - --------------------------------------------------------
> 2022-04-12 08:56:27,935 - MainThread - INFO - Sensitive operations are in progress!
> 2022-04-12 08:56:27,935 - MainThread - INFO - Please wait while the application is being shut down!
> 2022-04-12 08:56:27,935 - MainThread - INFO - --------------------------------------------------------
> 2022-04-12 08:56:27,935 - MainThread - INFO - Lock file removed!
> ```
> 
> As you can see the 465.csv report does not mark these as failed
> 
> ```
> address,type,amount,hash,paid,description
> tz1[snip],D,210,None,done,Payment amount < ZERO_THRESHOLD.
> tz1[snip],D,1237106,None,undefined,
> tz1[snip],D,908301,None,undefined,
> tz1[snip],D,171825,None,undefined,
> tz1[snip],D,31126,None,undefined,
> tz1[snip],D,10685,None,undefined,
> tz1[snip],M,2864379,None,undefined,
> ```
> 
> Tezos Wallet 2.2.15 Ledger Firmware 2.1.0, 1.12, 0.11
> 
> ```
> ~/tezos-reward-distributor$ git status
> On branch ithaca2
> Your branch is up to date with 'origin/ithaca2'.
> ```
> 
> Using the signer compiled from latest-release
> 
> ```
> ~/tezos$ git status
> On branch latest-release
> Your branch is up to date with 'origin/latest-release'.
> ```

**Comment by gregthebaker** [comment]
Upgrading the ledger tezos wallet app to version 2.3.2 fixed the issue

**Comment by songproducer** [comment]
Upgrading ledger tezos wallet fixed it for me too!
